/* Словникові дані: категорії та слова/фрази */
const CATEGORIES = [
  {
    id: 'basic', label: 'Базові слова і фрази', accent: '#3E5C76', icon: 'message-circle',
    words: [
      { en: 'Hello', ua: 'Привіт', ru: 'Привет' },
      { en: 'Goodbye', ua: 'До побачення', ru: 'До свидания' },
      { en: 'Please', ua: 'Будь ласка', ru: 'Пожалуйста' },
      { en: 'Thank you', ua: 'Дякую', ru: 'Спасибо' },
      { en: 'Yes', ua: 'Так', ru: 'Да' },
      { en: 'No', ua: 'Ні', ru: 'Нет' },
      { en: 'Excuse me', ua: 'Перепрошую', ru: 'Извините' },
      { en: 'Sorry', ua: 'Вибачте', ru: 'Простите' },
      { en: 'Good morning', ua: 'Доброго ранку', ru: 'Доброе утро' },
      { en: 'Good afternoon', ua: 'Добрий день', ru: 'Добрый день' },
      { en: 'Good night', ua: 'Добраніч', ru: 'Спокойной ночи' },
      { en: 'How are you?', ua: 'Як справи?', ru: 'Как дела?' },
      { en: 'My name is...', ua: 'Мене звати...', ru: 'Меня зовут...' },
      { en: 'What is your name?', ua: 'Як вас звати?', ru: 'Как вас зовут?' },
      { en: 'Nice to meet you', ua: 'Приємно познайомитися', ru: 'Приятно познакомиться' },
      { en: 'See you later', ua: 'До зустрічі', ru: 'До встречи' },
      { en: "I don't understand", ua: 'Я не розумію', ru: 'Я не понимаю' },
      { en: 'Do you speak English?', ua: 'Ви розмовляєте англійською?', ru: 'Вы говорите по-английски?' },
      { en: 'Slowly, please', ua: 'Повільніше, будь ласка', ru: 'Медленнее, пожалуйста' },
      { en: 'Where is...?', ua: 'Де знаходиться...?', ru: 'Где находится...?' },
      { en: 'How much does it cost?', ua: 'Скільки це коштує?', ru: 'Сколько это стоит?' },
      { en: 'I need...', ua: 'Мені потрібно...', ru: 'Мне нужно...' },
      { en: 'I am from Ukraine', ua: 'Я з України', ru: 'Я из Украины' },
      { en: 'Help', ua: 'Допомога', ru: 'Помощь' },
      { en: 'Water', ua: 'Вода', ru: 'Вода' },
    ]
  },
  {
    id: 'travel', label: 'В подорожі', accent: '#2F7A78', icon: 'plane',
    words: [
      { en: 'Airport', ua: 'Аеропорт', ru: 'Аэропорт' },
      { en: 'Ticket', ua: 'Квиток', ru: 'Билет' },
      { en: 'Passport', ua: 'Паспорт', ru: 'Паспорт' },
      { en: 'Visa', ua: 'Віза', ru: 'Виза' },
      { en: 'Luggage', ua: 'Багаж', ru: 'Багаж' },
      { en: 'Suitcase', ua: 'Валіза', ru: 'Чемодан' },
      { en: 'Flight', ua: 'Рейс', ru: 'Рейс' },
      { en: 'Delay', ua: 'Затримка', ru: 'Задержка' },
      { en: 'Gate', ua: 'Вихід на посадку', ru: 'Выход на посадку' },
      { en: 'Boarding pass', ua: 'Посадковий талон', ru: 'Посадочный талон' },
      { en: 'Customs', ua: 'Митниця', ru: 'Таможня' },
      { en: 'Arrival', ua: 'Прибуття', ru: 'Прибытие' },
      { en: 'Departure', ua: 'Відправлення', ru: 'Отправление' },
      { en: 'Train station', ua: 'Вокзал', ru: 'Вокзал' },
      { en: 'Platform', ua: 'Платформа', ru: 'Платформа' },
      { en: 'Map', ua: 'Карта', ru: 'Карта' },
      { en: 'Tourist', ua: 'Турист', ru: 'Турист' },
      { en: 'Currency exchange', ua: 'Обмін валют', ru: 'Обмен валют' },
    ]
  },
  {
    id: 'hotel', label: 'В готелі', accent: '#8B5A83', icon: 'bed',
    words: [
      { en: 'Reception', ua: 'Ресепшн', ru: 'Ресепшен' },
      { en: 'Front desk', ua: 'Стійка реєстрації', ru: 'Стойка регистрации' },
      { en: 'Room key', ua: 'Ключ від номера', ru: 'Ключ от номера' },
      { en: 'Check-in', ua: 'Заселення', ru: 'Заселение' },
      { en: 'Check-out', ua: 'Виселення', ru: 'Выселение' },
      { en: 'Reservation', ua: 'Бронювання', ru: 'Бронирование' },
      { en: 'Single room', ua: 'Одномісний номер', ru: 'Одноместный номер' },
      { en: 'Double room', ua: 'Двомісний номер', ru: 'Двухместный номер' },
      { en: 'Breakfast included', ua: 'Сніданок включено', ru: 'Завтрак включён' },
      { en: 'Wi-Fi password', ua: 'Пароль від Wi-Fi', ru: 'Пароль от Wi-Fi' },
      { en: 'Elevator', ua: 'Ліфт', ru: 'Лифт' },
      { en: 'Housekeeping', ua: 'Прибирання номера', ru: 'Уборка номера' },
      { en: 'Air conditioning', ua: 'Кондиціонер', ru: 'Кондиционер' },
      { en: 'Balcony', ua: 'Балкон', ru: 'Балкон' },
      { en: 'Towel', ua: 'Рушник', ru: 'Полотенце' },
      { en: 'Luggage storage', ua: 'Камера схову', ru: 'Камера хранения' },
    ]
  },
  {
    id: 'shopping', label: 'В магазині', accent: '#C4952F', icon: 'shopping-bag',
    words: [
      { en: 'Price', ua: 'Ціна', ru: 'Цена' },
      { en: 'Discount', ua: 'Знижка', ru: 'Скидка' },
      { en: 'Cash', ua: 'Готівка', ru: 'Наличные' },
      { en: 'Credit card', ua: 'Кредитна картка', ru: 'Кредитная карта' },
      { en: 'Receipt', ua: 'Чек', ru: 'Чек' },
      { en: 'Size', ua: 'Розмір', ru: 'Размер' },
      { en: 'Fitting room', ua: 'Примірочна', ru: 'Примерочная' },
      { en: 'Sale', ua: 'Розпродаж', ru: 'Распродажа' },
      { en: 'Cashier', ua: 'Касир', ru: 'Кассир' },
      { en: 'Shopping cart', ua: 'Візок', ru: 'Тележка' },
      { en: 'Refund', ua: 'Повернення коштів', ru: 'Возврат денег' },
      { en: 'Exchange', ua: 'Обмін товару', ru: 'Обмен товара' },
      { en: 'Queue', ua: 'Черга', ru: 'Очередь' },
      { en: 'Bag', ua: 'Пакет', ru: 'Пакет' },
      { en: 'Brand', ua: 'Бренд', ru: 'Бренд' },
      { en: 'Quality', ua: 'Якість', ru: 'Качество' },
      { en: 'Expensive', ua: 'Дорого', ru: 'Дорого' },
      { en: 'Cheap', ua: 'Дешево', ru: 'Дёшево' },
    ]
  },
  {
    id: 'school', label: 'В школі', accent: '#6B8F5A', icon: 'backpack',
    words: [
      { en: 'Teacher', ua: 'Вчитель', ru: 'Учитель' },
      { en: 'Student', ua: 'Учень', ru: 'Ученик' },
      { en: 'Classmate', ua: 'Однокласник', ru: 'Одноклассник' },
      { en: 'Classroom', ua: 'Клас', ru: 'Класс' },
      { en: 'Homework', ua: 'Домашнє завдання', ru: 'Домашнее задание' },
      { en: 'Textbook', ua: 'Підручник', ru: 'Учебник' },
      { en: 'Notebook', ua: 'Зошит', ru: 'Тетрадь' },
      { en: 'Pencil', ua: 'Олівець', ru: 'Карандаш' },
      { en: 'Ruler', ua: 'Лінійка', ru: 'Линейка' },
      { en: 'Exam', ua: 'Іспит', ru: 'Экзамен' },
      { en: 'Grade', ua: 'Оцінка', ru: 'Оценка' },
      { en: 'Lesson', ua: 'Урок', ru: 'Урок' },
      { en: 'Blackboard', ua: 'Дошка', ru: 'Доска' },
      { en: 'Break', ua: 'Перерва', ru: 'Перемена' },
      { en: 'Principal', ua: 'Директор школи', ru: 'Директор школы' },
    ]
  },
  {
    id: 'university', label: 'В університеті', accent: '#5B5EA6', icon: 'landmark',
    words: [
      { en: 'Lecture', ua: 'Лекція', ru: 'Лекция' },
      { en: 'Professor', ua: 'Професор', ru: 'Профессор' },
      { en: 'Faculty', ua: 'Факультет', ru: 'Факультет' },
      { en: 'Major', ua: 'Спеціальність', ru: 'Специальность' },
      { en: 'Dormitory', ua: 'Гуртожиток', ru: 'Общежитие' },
      { en: 'Scholarship', ua: 'Стипендія', ru: 'Стипендия' },
      { en: 'Grant', ua: 'Грант', ru: 'Грант' },
      { en: 'Degree', ua: 'Диплом', ru: 'Диплом' },
      { en: 'Thesis', ua: 'Дипломна робота', ru: 'Дипломная работа' },
      { en: 'Semester', ua: 'Семестр', ru: 'Семестр' },
      { en: 'Campus', ua: 'Кампус', ru: 'Кампус' },
      { en: 'Library', ua: 'Бібліотека', ru: 'Библиотека' },
      { en: 'Assignment', ua: 'Завдання', ru: 'Задание' },
      { en: 'Group mate', ua: 'Одногрупник', ru: 'Одногруппник' },
    ]
  },
  {
    id: 'work', label: 'На роботі', accent: '#566270', icon: 'briefcase',
    words: [
      { en: 'Meeting', ua: 'Нарада', ru: 'Совещание' },
      { en: 'Deadline', ua: 'Дедлайн', ru: 'Дедлайн' },
      { en: 'Salary', ua: 'Зарплата', ru: 'Зарплата' },
      { en: 'Colleague', ua: 'Колега', ru: 'Коллега' },
      { en: 'Boss', ua: 'Керівник', ru: 'Начальник' },
      { en: 'Team', ua: 'Команда', ru: 'Команда' },
      { en: 'Office', ua: 'Офіс', ru: 'Офис' },
      { en: 'Resume', ua: 'Резюме', ru: 'Резюме' },
      { en: 'Interview', ua: 'Співбесіда', ru: 'Собеседование' },
      { en: 'Contract', ua: 'Контракт', ru: 'Контракт' },
      { en: 'Project', ua: 'Проєкт', ru: 'Проект' },
      { en: 'Task', ua: 'Завдання', ru: 'Задача' },
      { en: 'Report', ua: 'Звіт', ru: 'Отчёт' },
      { en: 'Email', ua: 'Електронна пошта', ru: 'Электронная почта' },
      { en: 'Schedule', ua: 'Графік', ru: 'Расписание' },
      { en: 'Promotion', ua: 'Підвищення', ru: 'Повышение' },
      { en: 'Vacation', ua: 'Відпустка', ru: 'Отпуск' },
      { en: 'Overtime', ua: 'Понаднормова робота', ru: 'Сверхурочная работа' },
    ]
  },
  {
    id: 'phone', label: 'Дзвінок', accent: '#B15E5E', icon: 'phone',
    words: [
      { en: 'Hello? (on phone)', ua: 'Алло', ru: 'Алло' },
      { en: 'Can I speak to...', ua: 'Можна поговорити з...', ru: 'Можно поговорить с...' },
      { en: 'Hold on', ua: 'Зачекайте', ru: 'Подождите' },
      { en: 'Wrong number', ua: 'Помилились номером', ru: 'Ошиблись номером' },
      { en: 'Voicemail', ua: 'Голосова пошта', ru: 'Голосовая почта' },
      { en: 'Call back', ua: 'Передзвонити', ru: 'Перезвонить' },
      { en: 'Missed call', ua: 'Пропущений виклик', ru: 'Пропущенный вызов' },
      { en: 'Busy line', ua: 'Лінія зайнята', ru: 'Линия занята' },
      { en: 'Text message', ua: 'СМС-повідомлення', ru: 'СМС-сообщение' },
      { en: 'Video call', ua: 'Відеодзвінок', ru: 'Видеозвонок' },
      { en: 'Signal', ua: 'Сигнал', ru: 'Сигнал' },
      { en: 'Battery', ua: 'Акумулятор', ru: 'Аккумулятор' },
      { en: 'Charger', ua: 'Зарядний пристрій', ru: 'Зарядное устройство' },
      { en: 'Contact', ua: 'Контакт', ru: 'Контакт' },
    ]
  },
  {
    id: 'picnic', label: 'На пікніку', accent: '#8C9440', icon: 'tree-pine',
    words: [
      { en: 'Basket', ua: 'Кошик', ru: 'Корзина' },
      { en: 'Blanket', ua: 'Плед', ru: 'Плед' },
      { en: 'Sandwich', ua: 'Бутерброд', ru: 'Бутерброд' },
      { en: 'Thermos', ua: 'Термос', ru: 'Термос' },
      { en: 'Campfire', ua: 'Багаття', ru: 'Костёр' },
      { en: 'Grill', ua: 'Гриль', ru: 'Гриль' },
      { en: 'Ants', ua: 'Мурахи', ru: 'Муравьи' },
      { en: 'Sunscreen', ua: 'Сонцезахисний крем', ru: 'Солнцезащитный крем' },
      { en: 'Folding chair', ua: 'Розкладний стілець', ru: 'Складной стул' },
      { en: 'Napkin', ua: 'Серветка', ru: 'Салфетка' },
      { en: 'Cooler bag', ua: 'Сумка-холодильник', ru: 'Сумка-холодильник' },
      { en: 'Fruit', ua: 'Фрукти', ru: 'Фрукты' },
      { en: 'Juice', ua: 'Сік', ru: 'Сок' },
      { en: 'Backpack', ua: 'Рюкзак', ru: 'Рюкзак' },
    ]
  },
  {
    id: 'beach', label: 'На пляжі', accent: '#3FA0AE', icon: 'umbrella',
    words: [
      { en: 'Sand', ua: 'Пісок', ru: 'Песок' },
      { en: 'Wave', ua: 'Хвиля', ru: 'Волна' },
      { en: 'Swimsuit', ua: 'Купальник', ru: 'Купальник' },
      { en: 'Towel', ua: 'Рушник', ru: 'Полотенце' },
      { en: 'Umbrella', ua: 'Парасолька', ru: 'Зонт' },
      { en: 'Sunburn', ua: 'Сонячний опік', ru: 'Солнечный ожог' },
      { en: 'Lifeguard', ua: 'Рятувальник', ru: 'Спасатель' },
      { en: 'Snorkel', ua: 'Трубка для снорклінгу', ru: 'Трубка для сноркелинга' },
      { en: 'Shell', ua: 'Мушля', ru: 'Ракушка' },
      { en: 'Sunglasses', ua: "Сонцезахисні окуляри", ru: 'Солнцезащитные очки' },
      { en: 'Flip-flops', ua: "В'єтнамки", ru: 'Шлёпанцы' },
      { en: 'Tide', ua: 'Приплив', ru: 'Прилив' },
      { en: 'Seagull', ua: 'Чайка', ru: 'Чайка' },
      { en: 'Beach ball', ua: "Пляжний м'яч", ru: 'Пляжный мяч' },
    ]
  },
  {
    id: 'cafe', label: 'В кафе, ресторані', accent: '#7A5230', icon: 'coffee',
    words: [
      { en: 'Menu', ua: 'Меню', ru: 'Меню' },
      { en: 'Waiter', ua: 'Офіціант', ru: 'Официант' },
      { en: 'Order', ua: 'Замовлення', ru: 'Заказ' },
      { en: 'Appetizer', ua: 'Закуска', ru: 'Закуска' },
      { en: 'Main course', ua: 'Основна страва', ru: 'Основное блюдо' },
      { en: 'Dessert', ua: 'Десерт', ru: 'Десерт' },
      { en: 'Drink', ua: 'Напій', ru: 'Напиток' },
      { en: 'Bill', ua: 'Рахунок', ru: 'Счёт' },
      { en: 'Tip', ua: 'Чайові', ru: 'Чаевые' },
      { en: 'Table for two', ua: 'Столик на двох', ru: 'Столик на двоих' },
      { en: 'Takeaway', ua: 'На виніс', ru: 'На вынос' },
      { en: 'Reservation', ua: 'Бронювання столика', ru: 'Бронирование столика' },
      { en: 'Spicy', ua: 'Гостре', ru: 'Острое' },
      { en: 'Vegetarian', ua: 'Вегетаріанська страва', ru: 'Вегетарианское блюдо' },
      { en: 'Allergy', ua: 'Алергія', ru: 'Аллергия' },
      { en: 'Cutlery', ua: 'Столові прибори', ru: 'Столовые приборы' },
      { en: 'Napkin', ua: 'Серветка', ru: 'Салфетка' },
      { en: 'Delicious', ua: 'Смачно', ru: 'Вкусно' },
    ]
  },
  {
    id: 'car', label: 'В авто', accent: '#3E6A8C', icon: 'car',
    words: [
      { en: 'Steering wheel', ua: 'Кермо', ru: 'Руль' },
      { en: 'Seatbelt', ua: 'Ремінь безпеки', ru: 'Ремень безопасности' },
      { en: 'Engine', ua: 'Двигун', ru: 'Двигатель' },
      { en: 'Brake', ua: 'Гальмо', ru: 'Тормоз' },
      { en: 'Mirror', ua: 'Дзеркало', ru: 'Зеркало' },
      { en: 'Fuel', ua: 'Пальне', ru: 'Топливо' },
      { en: 'Gas station', ua: 'Заправка', ru: 'Заправка' },
      { en: 'Traffic jam', ua: 'Затор', ru: 'Пробка' },
      { en: 'Highway', ua: 'Автомагістраль', ru: 'Автомагистраль' },
      { en: 'Roundabout', ua: "Кільцева розв'язка", ru: 'Кольцевая развязка' },
      { en: 'Parking', ua: 'Парковка', ru: 'Парковка' },
      { en: "Driver's license", ua: 'Водійські права', ru: 'Водительские права' },
      { en: 'Insurance', ua: 'Страхування', ru: 'Страхование' },
      { en: 'Speed limit', ua: 'Обмеження швидкості', ru: 'Ограничение скорости' },
      { en: 'Trunk', ua: 'Багажник', ru: 'Багажник' },
      { en: 'Flat tire', ua: 'Проколота шина', ru: 'Спущенная шина' },
      { en: 'Mechanic', ua: 'Автомеханік', ru: 'Автомеханик' },
      { en: 'Windshield', ua: 'Лобове скло', ru: 'Лобовое стекло' },
    ]
  },
  {
    id: 'health', label: 'У лікаря, в аптеці', accent: '#A13F55', icon: 'plus-circle',
    words: [
      { en: 'Doctor', ua: 'Лікар', ru: 'Врач' },
      { en: 'Nurse', ua: 'Медсестра', ru: 'Медсестра' },
      { en: 'Hospital', ua: 'Лікарня', ru: 'Больница' },
      { en: 'Pharmacy', ua: 'Аптека', ru: 'Аптека' },
      { en: 'Medicine', ua: 'Ліки', ru: 'Лекарство' },
      { en: 'Prescription', ua: 'Рецепт', ru: 'Рецепт' },
      { en: 'Appointment', ua: 'Запис до лікаря', ru: 'Запись к врачу' },
      { en: 'Pain', ua: 'Біль', ru: 'Боль' },
      { en: 'Headache', ua: 'Головний біль', ru: 'Головная боль' },
      { en: 'Fever', ua: 'Гарячка', ru: 'Жар' },
      { en: 'Symptom', ua: 'Симптом', ru: 'Симптом' },
      { en: 'Injection', ua: 'Укол', ru: 'Укол' },
      { en: 'Bandage', ua: 'Бинт', ru: 'Бинт' },
      { en: 'Allergy', ua: 'Алергія', ru: 'Аллергия' },
      { en: 'Blood pressure', ua: 'Тиск крові', ru: 'Давление крови' },
      { en: 'Ambulance', ua: 'Швидка допомога', ru: 'Скорая помощь' },
    ]
  },
  {
    id: 'weather', label: 'Погода', accent: '#6D8CAE', icon: 'cloud',
    words: [
      { en: 'Sunny', ua: 'Сонячно', ru: 'Солнечно' },
      { en: 'Rainy', ua: 'Дощово', ru: 'Дождливо' },
      { en: 'Cloudy', ua: 'Хмарно', ru: 'Облачно' },
      { en: 'Windy', ua: 'Вітряно', ru: 'Ветрено' },
      { en: 'Snow', ua: 'Сніг', ru: 'Снег' },
      { en: 'Fog', ua: 'Туман', ru: 'Туман' },
      { en: 'Storm', ua: 'Гроза', ru: 'Гроза' },
      { en: 'Rainbow', ua: 'Веселка', ru: 'Радуга' },
      { en: 'Temperature', ua: 'Температура', ru: 'Температура' },
      { en: 'Forecast', ua: 'Прогноз погоди', ru: 'Прогноз погоды' },
      { en: 'Cold', ua: 'Холодно', ru: 'Холодно' },
      { en: 'Hot', ua: 'Спекотно', ru: 'Жарко' },
    ]
  },
  {
    id: 'family', label: 'Родина', accent: '#B0793A', icon: 'users',
    words: [
      { en: 'Mother', ua: 'Мама', ru: 'Мама' },
      { en: 'Father', ua: 'Тато', ru: 'Папа' },
      { en: 'Parents', ua: 'Батьки', ru: 'Родители' },
      { en: 'Sister', ua: 'Сестра', ru: 'Сестра' },
      { en: 'Brother', ua: 'Брат', ru: 'Брат' },
      { en: 'Son', ua: 'Син', ru: 'Сын' },
      { en: 'Daughter', ua: 'Донька', ru: 'Дочь' },
      { en: 'Child', ua: 'Дитина', ru: 'Ребёнок' },
      { en: 'Husband', ua: 'Чоловік', ru: 'Муж' },
      { en: 'Wife', ua: 'Дружина', ru: 'Жена' },
      { en: 'Grandmother', ua: 'Бабуся', ru: 'Бабушка' },
      { en: 'Grandfather', ua: 'Дідусь', ru: 'Дедушка' },
      { en: 'Aunt', ua: 'Тітка', ru: 'Тётя' },
      { en: 'Uncle', ua: 'Дядько', ru: 'Дядя' },
    ]
  },
  {
    id: 'numbers', label: 'Числа', accent: '#4E7A6B', icon: 'hash',
    words: [
      { en: 'Zero', ua: 'Нуль', ru: 'Ноль' },
      { en: 'One', ua: 'Один', ru: 'Один' },
      { en: 'Two', ua: 'Два', ru: 'Два' },
      { en: 'Three', ua: 'Три', ru: 'Три' },
      { en: 'Four', ua: 'Чотири', ru: 'Четыре' },
      { en: 'Five', ua: "П'ять", ru: 'Пять' },
      { en: 'Six', ua: 'Шість', ru: 'Шесть' },
      { en: 'Seven', ua: 'Сім', ru: 'Семь' },
      { en: 'Eight', ua: 'Вісім', ru: 'Восемь' },
      { en: 'Nine', ua: "Дев'ять", ru: 'Девять' },
      { en: 'Ten', ua: 'Десять', ru: 'Десять' },
      { en: 'Eleven', ua: 'Одинадцять', ru: 'Одиннадцать' },
      { en: 'Twelve', ua: 'Дванадцять', ru: 'Двенадцать' },
      { en: 'Fifteen', ua: "П'ятнадцять", ru: 'Пятнадцать' },
      { en: 'Twenty', ua: 'Двадцять', ru: 'Двадцать' },
      { en: 'Thirty', ua: 'Тридцять', ru: 'Тридцать' },
      { en: 'Forty', ua: 'Сорок', ru: 'Сорок' },
      { en: 'Fifty', ua: "П'ятдесят", ru: 'Пятьдесят' },
      { en: 'Sixty', ua: 'Шістдесят', ru: 'Шестьдесят' },
      { en: 'Seventy', ua: 'Сімдесят', ru: 'Семьдесят' },
      { en: 'Eighty', ua: 'Вісімдесят', ru: 'Восемьдесят' },
      { en: 'Ninety', ua: "Дев'яносто", ru: 'Девяносто' },
      { en: 'One hundred', ua: 'Сто', ru: 'Сто' },
      { en: 'One thousand', ua: 'Тисяча', ru: 'Тысяча' },
      { en: 'First', ua: 'Перший', ru: 'Первый' },
      { en: 'Second', ua: 'Другий', ru: 'Второй' },
    ]
  },
  {
    id: 'calendar', label: 'Дні, місяці, пори року', accent: '#4A8F6E', icon: 'calendar',
    words: [
      { en: 'Monday', ua: 'Понеділок', ru: 'Понедельник' },
      { en: 'Tuesday', ua: 'Вівторок', ru: 'Вторник' },
      { en: 'Wednesday', ua: 'Середа', ru: 'Среда' },
      { en: 'Thursday', ua: 'Четвер', ru: 'Четверг' },
      { en: 'Friday', ua: "П'ятниця", ru: 'Пятница' },
      { en: 'Saturday', ua: 'Субота', ru: 'Суббота' },
      { en: 'Sunday', ua: 'Неділя', ru: 'Воскресенье' },
      { en: 'January', ua: 'Січень', ru: 'Январь' },
      { en: 'February', ua: 'Лютий', ru: 'Февраль' },
      { en: 'March', ua: 'Березень', ru: 'Март' },
      { en: 'April', ua: 'Квітень', ru: 'Апрель' },
      { en: 'May', ua: 'Травень', ru: 'Май' },
      { en: 'June', ua: 'Червень', ru: 'Июнь' },
      { en: 'July', ua: 'Липень', ru: 'Июль' },
      { en: 'August', ua: 'Серпень', ru: 'Август' },
      { en: 'September', ua: 'Вересень', ru: 'Сентябрь' },
      { en: 'October', ua: 'Жовтень', ru: 'Октябрь' },
      { en: 'November', ua: 'Листопад', ru: 'Ноябрь' },
      { en: 'December', ua: 'Грудень', ru: 'Декабрь' },
      { en: 'Spring', ua: 'Весна', ru: 'Весна' },
      { en: 'Summer', ua: 'Літо', ru: 'Лето' },
      { en: 'Autumn', ua: 'Осінь', ru: 'Осень' },
      { en: 'Winter', ua: 'Зима', ru: 'Зима' },
    ]
  },
  {
    id: 'colors', label: 'Кольори', accent: '#8A5A9B', icon: 'palette',
    words: [
      { en: 'Red', ua: 'Червоний', ru: 'Красный' },
      { en: 'Blue', ua: 'Синій', ru: 'Синий' },
      { en: 'Green', ua: 'Зелений', ru: 'Зелёный' },
      { en: 'Yellow', ua: 'Жовтий', ru: 'Жёлтый' },
      { en: 'Black', ua: 'Чорний', ru: 'Чёрный' },
      { en: 'White', ua: 'Білий', ru: 'Белый' },
      { en: 'Orange', ua: 'Помаранчевий', ru: 'Оранжевый' },
      { en: 'Purple', ua: 'Фіолетовий', ru: 'Фиолетовый' },
      { en: 'Pink', ua: 'Рожевий', ru: 'Розовый' },
      { en: 'Brown', ua: 'Коричневий', ru: 'Коричневый' },
      { en: 'Grey', ua: 'Сірий', ru: 'Серый' },
      { en: 'Beige', ua: 'Бежевий', ru: 'Бежевый' },
      { en: 'Turquoise', ua: 'Бірюзовий', ru: 'Бирюзовый' },
      { en: 'Gold', ua: 'Золотий', ru: 'Золотой' },
    ]
  },
  {
    id: 'animals', label: 'Тварини', accent: '#7A5A3E', icon: 'paw',
    words: [
      { en: 'Dog', ua: 'Собака', ru: 'Собака' },
      { en: 'Cat', ua: 'Кіт', ru: 'Кот' },
      { en: 'Bird', ua: 'Птах', ru: 'Птица' },
      { en: 'Fish', ua: 'Риба', ru: 'Рыба' },
      { en: 'Horse', ua: 'Кінь', ru: 'Лошадь' },
      { en: 'Cow', ua: 'Корова', ru: 'Корова' },
      { en: 'Pig', ua: 'Свиня', ru: 'Свинья' },
      { en: 'Sheep', ua: 'Вівця', ru: 'Овца' },
      { en: 'Chicken', ua: 'Курка', ru: 'Курица' },
      { en: 'Rabbit', ua: 'Кролик', ru: 'Кролик' },
      { en: 'Mouse', ua: 'Миша', ru: 'Мышь' },
      { en: 'Bear', ua: 'Ведмідь', ru: 'Медведь' },
      { en: 'Wolf', ua: 'Вовк', ru: 'Волк' },
      { en: 'Fox', ua: 'Лисиця', ru: 'Лиса' },
      { en: 'Deer', ua: 'Олень', ru: 'Олень' },
      { en: 'Lion', ua: 'Лев', ru: 'Лев' },
      { en: 'Tiger', ua: 'Тигр', ru: 'Тигр' },
      { en: 'Elephant', ua: 'Слон', ru: 'Слон' },
      { en: 'Monkey', ua: 'Мавпа', ru: 'Обезьяна' },
      { en: 'Snake', ua: 'Змія', ru: 'Змея' },
      { en: 'Frog', ua: 'Жаба', ru: 'Лягушка' },
      { en: 'Butterfly', ua: 'Метелик', ru: 'Бабочка' },
      { en: 'Bee', ua: 'Бджола', ru: 'Пчела' },
      { en: 'Spider', ua: 'Павук', ru: 'Паук' },
      { en: 'Squirrel', ua: 'Білка', ru: 'Белка' },
      { en: 'Turtle', ua: 'Черепаха', ru: 'Черепаха' },
      { en: 'Duck', ua: 'Качка', ru: 'Утка' },
      { en: 'Owl', ua: 'Сова', ru: 'Сова' },
      { en: 'Dolphin', ua: 'Дельфін', ru: 'Дельфин' },
      { en: 'Shark', ua: 'Акула', ru: 'Акула' },
    ]
  },
  {
    id: 'food', label: 'Їжа та напої', accent: '#A66B2E', icon: 'utensils',
    words: [
      { en: 'Bread', ua: 'Хліб', ru: 'Хлеб' },
      { en: 'Milk', ua: 'Молоко', ru: 'Молоко' },
      { en: 'Egg', ua: 'Яйце', ru: 'Яйцо' },
      { en: 'Cheese', ua: 'Сир', ru: 'Сыр' },
      { en: 'Meat', ua: "М'ясо", ru: 'Мясо' },
      { en: 'Chicken meat', ua: 'Курятина', ru: 'Курятина' },
      { en: 'Rice', ua: 'Рис', ru: 'Рис' },
      { en: 'Pasta', ua: 'Паста', ru: 'Паста' },
      { en: 'Soup', ua: 'Суп', ru: 'Суп' },
      { en: 'Salad', ua: 'Салат', ru: 'Салат' },
      { en: 'Vegetables', ua: 'Овочі', ru: 'Овощи' },
      { en: 'Fruit', ua: 'Фрукти', ru: 'Фрукты' },
      { en: 'Apple', ua: 'Яблуко', ru: 'Яблоко' },
      { en: 'Banana', ua: 'Банан', ru: 'Банан' },
      { en: 'Orange', ua: 'Апельсин', ru: 'Апельсин' },
      { en: 'Potato', ua: 'Картопля', ru: 'Картофель' },
      { en: 'Tomato', ua: 'Помідор', ru: 'Помидор' },
      { en: 'Onion', ua: 'Цибуля', ru: 'Лук' },
      { en: 'Carrot', ua: 'Морква', ru: 'Морковь' },
      { en: 'Sugar', ua: 'Цукор', ru: 'Сахар' },
      { en: 'Salt', ua: 'Сіль', ru: 'Соль' },
      { en: 'Pepper', ua: 'Перець', ru: 'Перец' },
      { en: 'Butter', ua: 'Масло', ru: 'Масло' },
      { en: 'Coffee', ua: 'Кава', ru: 'Кофе' },
      { en: 'Tea', ua: 'Чай', ru: 'Чай' },
      { en: 'Wine', ua: 'Вино', ru: 'Вино' },
      { en: 'Beer', ua: 'Пиво', ru: 'Пиво' },
      { en: 'Ice cream', ua: 'Морозиво', ru: 'Мороженое' },
      { en: 'Cake', ua: 'Торт', ru: 'Торт' },
      { en: 'Chocolate', ua: 'Шоколад', ru: 'Шоколад' },
      { en: 'Honey', ua: 'Мед', ru: 'Мёд' },
      { en: 'Yogurt', ua: 'Йогурт', ru: 'Йогурт' },
    ]
  },
  {
    id: 'body', label: 'Частини тіла', accent: '#5B6B8C', icon: 'user',
    words: [
      { en: 'Head', ua: 'Голова', ru: 'Голова' },
      { en: 'Hair', ua: 'Волосся', ru: 'Волосы' },
      { en: 'Face', ua: 'Обличчя', ru: 'Лицо' },
      { en: 'Eye', ua: 'Око', ru: 'Глаз' },
      { en: 'Ear', ua: 'Вухо', ru: 'Ухо' },
      { en: 'Nose', ua: 'Ніс', ru: 'Нос' },
      { en: 'Mouth', ua: 'Рот', ru: 'Рот' },
      { en: 'Tooth', ua: 'Зуб', ru: 'Зуб' },
      { en: 'Lips', ua: 'Губи', ru: 'Губы' },
      { en: 'Neck', ua: 'Шия', ru: 'Шея' },
      { en: 'Shoulder', ua: 'Плече', ru: 'Плечо' },
      { en: 'Arm', ua: 'Рука', ru: 'Рука' },
      { en: 'Hand', ua: 'Долоня', ru: 'Кисть' },
      { en: 'Finger', ua: 'Палець', ru: 'Палец' },
      { en: 'Elbow', ua: 'Лікоть', ru: 'Локоть' },
      { en: 'Leg', ua: 'Нога', ru: 'Нога' },
      { en: 'Knee', ua: 'Коліно', ru: 'Колено' },
      { en: 'Foot', ua: 'Ступня', ru: 'Стопа' },
      { en: 'Back', ua: 'Спина', ru: 'Спина' },
      { en: 'Chest', ua: 'Груди', ru: 'Грудь' },
      { en: 'Stomach', ua: 'Живіт', ru: 'Живот' },
      { en: 'Heart', ua: 'Серце', ru: 'Сердце' },
      { en: 'Skin', ua: 'Шкіра', ru: 'Кожа' },
      { en: 'Bone', ua: 'Кістка', ru: 'Кость' },
    ]
  },
  {
    id: 'clothing', label: 'Одяг', accent: '#A3684F', icon: 'shirt',
    words: [
      { en: 'Shirt', ua: 'Сорочка', ru: 'Рубашка' },
      { en: 'T-shirt', ua: 'Футболка', ru: 'Футболка' },
      { en: 'Trousers', ua: 'Штани', ru: 'Брюки' },
      { en: 'Jeans', ua: 'Джинси', ru: 'Джинсы' },
      { en: 'Dress', ua: 'Сукня', ru: 'Платье' },
      { en: 'Skirt', ua: 'Спідниця', ru: 'Юбка' },
      { en: 'Jacket', ua: 'Куртка', ru: 'Куртка' },
      { en: 'Coat', ua: 'Пальто', ru: 'Пальто' },
      { en: 'Sweater', ua: 'Светр', ru: 'Свитер' },
      { en: 'Shoes', ua: 'Взуття', ru: 'Обувь' },
      { en: 'Boots', ua: 'Чоботи', ru: 'Сапоги' },
      { en: 'Sneakers', ua: 'Кросівки', ru: 'Кроссовки' },
      { en: 'Socks', ua: 'Шкарпетки', ru: 'Носки' },
      { en: 'Hat', ua: 'Капелюх', ru: 'Шляпа' },
      { en: 'Scarf', ua: 'Шарф', ru: 'Шарф' },
      { en: 'Gloves', ua: 'Рукавички', ru: 'Перчатки' },
      { en: 'Belt', ua: 'Ремінь', ru: 'Ремень' },
      { en: 'Underwear', ua: 'Спідня білизна', ru: 'Нижнее бельё' },
      { en: 'Suit', ua: 'Костюм', ru: 'Костюм' },
      { en: 'Pajamas', ua: 'Піжама', ru: 'Пижама' },
      { en: 'Raincoat', ua: 'Дощовик', ru: 'Дождевик' },
    ]
  },
  {
    id: 'house', label: 'Дім і меблі', accent: '#5C7A8A', icon: 'home',
    words: [
      { en: 'House', ua: 'Будинок', ru: 'Дом' },
      { en: 'Apartment', ua: 'Квартира', ru: 'Квартира' },
      { en: 'Room', ua: 'Кімната', ru: 'Комната' },
      { en: 'Kitchen', ua: 'Кухня', ru: 'Кухня' },
      { en: 'Bedroom', ua: 'Спальня', ru: 'Спальня' },
      { en: 'Bathroom', ua: 'Ванна кімната', ru: 'Ванная комната' },
      { en: 'Living room', ua: 'Вітальня', ru: 'Гостиная' },
      { en: 'Table', ua: 'Стіл', ru: 'Стол' },
      { en: 'Chair', ua: 'Стілець', ru: 'Стул' },
      { en: 'Sofa', ua: 'Диван', ru: 'Диван' },
      { en: 'Bed', ua: 'Ліжко', ru: 'Кровать' },
      { en: 'Wardrobe', ua: 'Шафа', ru: 'Шкаф' },
      { en: 'Shelf', ua: 'Полиця', ru: 'Полка' },
      { en: 'Lamp', ua: 'Лампа', ru: 'Лампа' },
      { en: 'Window', ua: 'Вікно', ru: 'Окно' },
      { en: 'Door', ua: 'Двері', ru: 'Дверь' },
      { en: 'Wall', ua: 'Стіна', ru: 'Стена' },
      { en: 'Floor', ua: 'Підлога', ru: 'Пол' },
      { en: 'Ceiling', ua: 'Стеля', ru: 'Потолок' },
      { en: 'Refrigerator', ua: 'Холодильник', ru: 'Холодильник' },
      { en: 'Stove', ua: 'Плита', ru: 'Плита' },
      { en: 'Curtains', ua: 'Штори', ru: 'Шторы' },
    ]
  },
  {
    id: 'professions', label: 'Професії', accent: '#6B7A8C', icon: 'briefcase',
    words: [
      { en: 'Engineer', ua: 'Інженер', ru: 'Инженер' },
      { en: 'Lawyer', ua: 'Юрист', ru: 'Юрист' },
      { en: 'Police officer', ua: 'Поліцейський', ru: 'Полицейский' },
      { en: 'Firefighter', ua: 'Пожежник', ru: 'Пожарный' },
      { en: 'Driver', ua: 'Водій', ru: 'Водитель' },
      { en: 'Cook', ua: 'Кухар', ru: 'Повар' },
      { en: 'Farmer', ua: 'Фермер', ru: 'Фермер' },
      { en: 'Builder', ua: 'Будівельник', ru: 'Строитель' },
      { en: 'Artist', ua: 'Художник', ru: 'Художник' },
      { en: 'Musician', ua: 'Музикант', ru: 'Музыкант' },
      { en: 'Writer', ua: 'Письменник', ru: 'Писатель' },
      { en: 'Programmer', ua: 'Програміст', ru: 'Программист' },
      { en: 'Accountant', ua: 'Бухгалтер', ru: 'Бухгалтер' },
      { en: 'Salesperson', ua: 'Продавець', ru: 'Продавец' },
      { en: 'Hairdresser', ua: 'Перукар', ru: 'Парикмахер' },
      { en: 'Pilot', ua: 'Пілот', ru: 'Пилот' },
      { en: 'Soldier', ua: 'Військовий', ru: 'Военный' },
      { en: 'Scientist', ua: 'Науковець', ru: 'Учёный' },
    ]
  },
  {
    id: 'verbs', label: 'Дієслова', accent: '#3E8E63', icon: 'zap',
    words: [
      { en: 'To be', ua: 'Бути', ru: 'Быть' },
      { en: 'To have', ua: 'Мати', ru: 'Иметь' },
      { en: 'To go', ua: 'Йти', ru: 'Идти' },
      { en: 'To come', ua: 'Приходити', ru: 'Приходить' },
      { en: 'To do', ua: 'Робити', ru: 'Делать' },
      { en: 'To make', ua: 'Створювати', ru: 'Создавать' },
      { en: 'To see', ua: 'Бачити', ru: 'Видеть' },
      { en: 'To look', ua: 'Дивитися', ru: 'Смотреть' },
      { en: 'To know', ua: 'Знати', ru: 'Знать' },
      { en: 'To think', ua: 'Думати', ru: 'Думать' },
      { en: 'To want', ua: 'Хотіти', ru: 'Хотеть' },
      { en: 'To need', ua: 'Потребувати', ru: 'Нуждаться' },
      { en: 'To like', ua: 'Подобатися', ru: 'Нравиться' },
      { en: 'To love', ua: 'Любити', ru: 'Любить' },
      { en: 'To eat', ua: 'Їсти', ru: 'Есть' },
      { en: 'To drink', ua: 'Пити', ru: 'Пить' },
      { en: 'To sleep', ua: 'Спати', ru: 'Спать' },
      { en: 'To work', ua: 'Працювати', ru: 'Работать' },
      { en: 'To study', ua: 'Навчатися', ru: 'Учиться' },
      { en: 'To read', ua: 'Читати', ru: 'Читать' },
      { en: 'To write', ua: 'Писати', ru: 'Писать' },
      { en: 'To speak', ua: 'Говорити', ru: 'Говорить' },
      { en: 'To listen', ua: 'Слухати', ru: 'Слушать' },
      { en: 'To buy', ua: 'Купувати', ru: 'Покупать' },
      { en: 'To sell', ua: 'Продавати', ru: 'Продавать' },
      { en: 'To give', ua: 'Давати', ru: 'Давать' },
      { en: 'To take', ua: 'Брати', ru: 'Брать' },
      { en: 'To play', ua: 'Грати', ru: 'Играть' },
      { en: 'To run', ua: 'Бігти', ru: 'Бежать' },
      { en: 'To walk', ua: 'Ходити', ru: 'Ходить' },
      { en: 'To sit', ua: 'Сидіти', ru: 'Сидеть' },
      { en: 'To stand', ua: 'Стояти', ru: 'Стоять' },
      { en: 'To open', ua: 'Відкривати', ru: 'Открывать' },
      { en: 'To close', ua: 'Закривати', ru: 'Закрывать' },
      { en: 'To help', ua: 'Допомагати', ru: 'Помогать' },
      { en: 'To wait', ua: 'Чекати', ru: 'Ждать' },
      { en: 'To live', ua: 'Жити', ru: 'Жить' },
      { en: 'To travel', ua: 'Подорожувати', ru: 'Путешествовать' },
      { en: 'To drive', ua: 'Керувати автомобілем', ru: 'Водить машину' },
      { en: 'To cook', ua: 'Готувати', ru: 'Готовить' },
    ]
  },
  {
    id: 'adjectives', label: 'Прикметники', accent: '#8C6B3E', icon: 'sliders',
    words: [
      { en: 'Big', ua: 'Великий', ru: 'Большой' },
      { en: 'Small', ua: 'Маленький', ru: 'Маленький' },
      { en: 'Good', ua: 'Хороший', ru: 'Хороший' },
      { en: 'Bad', ua: 'Поганий', ru: 'Плохой' },
      { en: 'New', ua: 'Новий', ru: 'Новый' },
      { en: 'Old', ua: 'Старий', ru: 'Старый' },
      { en: 'Fast', ua: 'Швидкий', ru: 'Быстрый' },
      { en: 'Slow', ua: 'Повільний', ru: 'Медленный' },
      { en: 'Happy', ua: 'Щасливий', ru: 'Счастливый' },
      { en: 'Sad', ua: 'Сумний', ru: 'Грустный' },
      { en: 'Beautiful', ua: 'Гарний', ru: 'Красивый' },
      { en: 'Ugly', ua: 'Потворний', ru: 'Некрасивый' },
      { en: 'Easy', ua: 'Легкий', ru: 'Лёгкий' },
      { en: 'Difficult', ua: 'Складний', ru: 'Сложный' },
      { en: 'Strong', ua: 'Сильний', ru: 'Сильный' },
      { en: 'Weak', ua: 'Слабкий', ru: 'Слабый' },
      { en: 'Hot', ua: 'Гарячий', ru: 'Горячий' },
      { en: 'Cold', ua: 'Холодний', ru: 'Холодный' },
      { en: 'Clean', ua: 'Чистий', ru: 'Чистый' },
      { en: 'Dirty', ua: 'Брудний', ru: 'Грязный' },
      { en: 'Full', ua: 'Повний', ru: 'Полный' },
      { en: 'Empty', ua: 'Порожній', ru: 'Пустой' },
      { en: 'Rich', ua: 'Багатий', ru: 'Богатый' },
      { en: 'Poor', ua: 'Бідний', ru: 'Бедный' },
      { en: 'Tall', ua: 'Високий', ru: 'Высокий' },
      { en: 'Short', ua: 'Низький', ru: 'Низкий' },
      { en: 'Long', ua: 'Довгий', ru: 'Длинный' },
      { en: 'Heavy', ua: 'Важкий', ru: 'Тяжёлый' },
      { en: 'Light', ua: 'Легкий', ru: 'Лёгкий' },
      { en: 'Interesting', ua: 'Цікавий', ru: 'Интересный' },
    ]
  },
  {
    id: 'emotions', label: 'Емоції', accent: '#B15E8C', icon: 'smile',
    words: [
      { en: 'Angry', ua: 'Злий', ru: 'Злой' },
      { en: 'Afraid', ua: 'Наляканий', ru: 'Испуганный' },
      { en: 'Surprised', ua: 'Здивований', ru: 'Удивлённый' },
      { en: 'Tired', ua: 'Втомлений', ru: 'Уставший' },
      { en: 'Bored', ua: 'Знуджений', ru: 'Скучающий' },
      { en: 'Excited', ua: 'Схвильований', ru: 'Взволнованный' },
      { en: 'Calm', ua: 'Спокійний', ru: 'Спокойный' },
      { en: 'Nervous', ua: 'Нервовий', ru: 'Нервный' },
      { en: 'Proud', ua: 'Гордий', ru: 'Гордый' },
      { en: 'Confused', ua: 'Спантеличений', ru: 'Растерянный' },
      { en: 'Jealous', ua: 'Ревнивий', ru: 'Ревнивый' },
      { en: 'Grateful', ua: 'Вдячний', ru: 'Благодарный' },
      { en: 'Lonely', ua: 'Самотній', ru: 'Одинокий' },
      { en: 'Confident', ua: 'Впевнений', ru: 'Уверенный' },
      { en: 'Worried', ua: 'Стурбований', ru: 'Обеспокоенный' },
      { en: 'Curious', ua: 'Допитливий', ru: 'Любопытный' },
    ]
  },
  {
    id: 'transport', label: 'Транспорт', accent: '#3E7A8C', icon: 'truck',
    words: [
      { en: 'Bus', ua: 'Автобус', ru: 'Автобус' },
      { en: 'Train', ua: 'Потяг', ru: 'Поезд' },
      { en: 'Tram', ua: 'Трамвай', ru: 'Трамвай' },
      { en: 'Trolleybus', ua: 'Тролейбус', ru: 'Троллейбус' },
      { en: 'Subway', ua: 'Метро', ru: 'Метро' },
      { en: 'Taxi', ua: 'Таксі', ru: 'Такси' },
      { en: 'Bicycle', ua: 'Велосипед', ru: 'Велосипед' },
      { en: 'Motorcycle', ua: 'Мотоцикл', ru: 'Мотоцикл' },
      { en: 'Ship', ua: 'Корабель', ru: 'Корабль' },
      { en: 'Boat', ua: 'Човен', ru: 'Лодка' },
      { en: 'Ferry', ua: 'Пором', ru: 'Паром' },
      { en: 'Truck', ua: 'Вантажівка', ru: 'Грузовик' },
      { en: 'Fare', ua: 'Проїзд', ru: 'Проезд' },
      { en: 'Bus stop', ua: 'Зупинка', ru: 'Остановка' },
      { en: 'Driver', ua: 'Водій', ru: 'Водитель' },
      { en: 'Passenger', ua: 'Пасажир', ru: 'Пассажир' },
      { en: 'Route', ua: 'Маршрут', ru: 'Маршрут' },
      { en: 'Traffic light', ua: 'Світлофор', ru: 'Светофор' },
      { en: 'Pedestrian', ua: 'Пішохід', ru: 'Пешеход' },
      { en: 'Crosswalk', ua: 'Пішохідний перехід', ru: 'Пешеходный переход' },
    ]
  },
  {
    id: 'city', label: 'Місто й орієнтування', accent: '#6B5A8C', icon: 'map-pin',
    words: [
      { en: 'City', ua: 'Місто', ru: 'Город' },
      { en: 'Street', ua: 'Вулиця', ru: 'Улица' },
      { en: 'Avenue', ua: 'Проспект', ru: 'Проспект' },
      { en: 'Square', ua: 'Площа', ru: 'Площадь' },
      { en: 'Bridge', ua: 'Міст', ru: 'Мост' },
      { en: 'Park', ua: 'Парк', ru: 'Парк' },
      { en: 'Church', ua: 'Церква', ru: 'Церковь' },
      { en: 'Museum', ua: 'Музей', ru: 'Музей' },
      { en: 'Theater', ua: 'Театр', ru: 'Театр' },
      { en: 'Cinema', ua: 'Кінотеатр', ru: 'Кинотеатр' },
      { en: 'Bank', ua: 'Банк', ru: 'Банк' },
      { en: 'Post office', ua: 'Пошта', ru: 'Почта' },
      { en: 'Police station', ua: 'Відділок поліції', ru: 'Полицейский участок' },
      { en: 'Market', ua: 'Ринок', ru: 'Рынок' },
      { en: 'Stadium', ua: 'Стадіон', ru: 'Стадион' },
      { en: 'Zoo', ua: 'Зоопарк', ru: 'Зоопарк' },
      { en: 'Neighborhood', ua: 'Район', ru: 'Район' },
      { en: 'Left', ua: 'Ліворуч', ru: 'Налево' },
      { en: 'Right', ua: 'Праворуч', ru: 'Направо' },
      { en: 'Straight ahead', ua: 'Прямо', ru: 'Прямо' },
      { en: 'Near', ua: 'Поруч', ru: 'Рядом' },
      { en: 'Far', ua: 'Далеко', ru: 'Далеко' },
      { en: 'Corner', ua: 'Ріг вулиці', ru: 'Угол улицы' },
      { en: 'Traffic', ua: 'Дорожній рух', ru: 'Дорожное движение' },
      { en: 'Sidewalk', ua: 'Тротуар', ru: 'Тротуар' },
    ]
  },
  {
    id: 'tech', label: 'Технології та гаджети', accent: '#4A6B8C', icon: 'cpu',
    words: [
      { en: 'Computer', ua: "Комп'ютер", ru: 'Компьютер' },
      { en: 'Laptop', ua: 'Ноутбук', ru: 'Ноутбук' },
      { en: 'Phone', ua: 'Телефон', ru: 'Телефон' },
      { en: 'Smartphone', ua: 'Смартфон', ru: 'Смартфон' },
      { en: 'Tablet', ua: 'Планшет', ru: 'Планшет' },
      { en: 'Internet', ua: 'Інтернет', ru: 'Интернет' },
      { en: 'Wi-Fi', ua: 'Wi-Fi', ru: 'Wi-Fi' },
      { en: 'Password', ua: 'Пароль', ru: 'Пароль' },
      { en: 'Application', ua: 'Додаток', ru: 'Приложение' },
      { en: 'Website', ua: 'Вебсайт', ru: 'Веб-сайт' },
      { en: 'Screen', ua: 'Екран', ru: 'Экран' },
      { en: 'Keyboard', ua: 'Клавіатура', ru: 'Клавиатура' },
      { en: 'Computer mouse', ua: "Комп'ютерна миша", ru: 'Компьютерная мышь' },
      { en: 'Camera', ua: 'Камера', ru: 'Камера' },
      { en: 'Headphones', ua: 'Навушники', ru: 'Наушники' },
      { en: 'Printer', ua: 'Принтер', ru: 'Принтер' },
      { en: 'Software', ua: 'Програмне забезпечення', ru: 'Программное обеспечение' },
      { en: 'File', ua: 'Файл', ru: 'Файл' },
      { en: 'Download', ua: 'Завантажити', ru: 'Скачать' },
      { en: 'Upload', ua: 'Завантажити на сервер', ru: 'Загрузить' },
      { en: 'Update', ua: 'Оновлення', ru: 'Обновление' },
      { en: 'Settings', ua: 'Налаштування', ru: 'Настройки' },
      { en: 'Account', ua: 'Обліковий запис', ru: 'Учётная запись' },
      { en: 'Charger', ua: 'Зарядний пристрій', ru: 'Зарядное устройство' },
      { en: 'Battery', ua: 'Акумулятор', ru: 'Аккумулятор' },
    ]
  },
  {
    id: 'nature', label: 'Природа та довкілля', accent: '#4E8C5A', icon: 'leaf',
    words: [
      { en: 'Forest', ua: 'Ліс', ru: 'Лес' },
      { en: 'Mountain', ua: 'Гора', ru: 'Гора' },
      { en: 'River', ua: 'Річка', ru: 'Река' },
      { en: 'Lake', ua: 'Озеро', ru: 'Озеро' },
      { en: 'Sea', ua: 'Море', ru: 'Море' },
      { en: 'Ocean', ua: 'Океан', ru: 'Океан' },
      { en: 'Sky', ua: 'Небо', ru: 'Небо' },
      { en: 'Sun', ua: 'Сонце', ru: 'Солнце' },
      { en: 'Moon', ua: 'Місяць', ru: 'Луна' },
      { en: 'Star', ua: 'Зірка', ru: 'Звезда' },
      { en: 'Cloud', ua: 'Хмара', ru: 'Облако' },
      { en: 'Rain', ua: 'Дощ', ru: 'Дождь' },
      { en: 'Wind', ua: 'Вітер', ru: 'Ветер' },
      { en: 'Tree', ua: 'Дерево', ru: 'Дерево' },
      { en: 'Flower', ua: 'Квітка', ru: 'Цветок' },
      { en: 'Grass', ua: 'Трава', ru: 'Трава' },
      { en: 'Leaf', ua: 'Листок', ru: 'Лист' },
      { en: 'Stone', ua: 'Камінь', ru: 'Камень' },
      { en: 'Island', ua: 'Острів', ru: 'Остров' },
      { en: 'Valley', ua: 'Долина', ru: 'Долина' },
      { en: 'Field', ua: 'Поле', ru: 'Поле' },
      { en: 'Desert', ua: 'Пустеля', ru: 'Пустыня' },
      { en: 'Volcano', ua: 'Вулкан', ru: 'Вулкан' },
      { en: 'Waterfall', ua: 'Водоспад', ru: 'Водопад' },
      { en: 'Earth', ua: 'Земля', ru: 'Земля' },
    ]
  },
  {
    id: 'sports', label: 'Спорт', accent: '#C4682F', icon: 'award',
    words: [
      { en: 'Football', ua: 'Футбол', ru: 'Футбол' },
      { en: 'Basketball', ua: 'Баскетбол', ru: 'Баскетбол' },
      { en: 'Tennis', ua: 'Теніс', ru: 'Теннис' },
      { en: 'Volleyball', ua: 'Волейбол', ru: 'Волейбол' },
      { en: 'Swimming', ua: 'Плавання', ru: 'Плавание' },
      { en: 'Running', ua: 'Біг', ru: 'Бег' },
      { en: 'Cycling', ua: 'Велоспорт', ru: 'Велоспорт' },
      { en: 'Boxing', ua: 'Бокс', ru: 'Бокс' },
      { en: 'Skiing', ua: 'Лижі', ru: 'Лыжи' },
      { en: 'Skating', ua: 'Ковзани', ru: 'Коньки' },
      { en: 'Gym', ua: 'Спортзал', ru: 'Спортзал' },
      { en: 'Coach', ua: 'Тренер', ru: 'Тренер' },
      { en: 'Team', ua: 'Команда', ru: 'Команда' },
      { en: 'Match', ua: 'Матч', ru: 'Матч' },
      { en: 'Score', ua: 'Рахунок', ru: 'Счёт' },
      { en: 'Goal', ua: 'Гол', ru: 'Гол' },
      { en: 'Champion', ua: 'Чемпіон', ru: 'Чемпион' },
      { en: 'Medal', ua: 'Медаль', ru: 'Медаль' },
      { en: 'Competition', ua: 'Змагання', ru: 'Соревнование' },
      { en: 'Referee', ua: 'Суддя', ru: 'Судья' },
      { en: 'Training', ua: 'Тренування', ru: 'Тренировка' },
      { en: 'Victory', ua: 'Перемога', ru: 'Победа' },
      { en: 'Defeat', ua: 'Поразка', ru: 'Поражение' },
      { en: 'Fitness', ua: 'Фітнес', ru: 'Фитнес' },
      { en: 'Ball', ua: "М'яч", ru: 'Мяч' },
    ]
  },
  {
    id: 'holidays', label: 'Свята та події', accent: '#A13F7A', icon: 'gift',
    words: [
      { en: 'Holiday', ua: 'Свято', ru: 'Праздник' },
      { en: 'Birthday', ua: 'День народження', ru: 'День рождения' },
      { en: 'Christmas', ua: 'Різдво', ru: 'Рождество' },
      { en: 'New Year', ua: 'Новий рік', ru: 'Новый год' },
      { en: 'Easter', ua: 'Великдень', ru: 'Пасха' },
      { en: 'Wedding', ua: 'Весілля', ru: 'Свадьба' },
      { en: 'Gift', ua: 'Подарунок', ru: 'Подарок' },
      { en: 'Party', ua: 'Вечірка', ru: 'Вечеринка' },
      { en: 'Celebration', ua: 'Святкування', ru: 'Празднование' },
      { en: 'Congratulations', ua: 'Вітання', ru: 'Поздравления' },
      { en: 'Guest', ua: 'Гість', ru: 'Гость' },
      { en: 'Invitation', ua: 'Запрошення', ru: 'Приглашение' },
      { en: 'Candle', ua: 'Свічка', ru: 'Свеча' },
      { en: 'Fireworks', ua: 'Феєрверк', ru: 'Фейерверк' },
      { en: 'Tradition', ua: 'Традиція', ru: 'Традиция' },
      { en: 'Anniversary', ua: 'Річниця', ru: 'Годовщина' },
      { en: 'Toast', ua: 'Тост', ru: 'Тост' },
      { en: 'Balloon', ua: 'Повітряна кулька', ru: 'Воздушный шарик' },
      { en: 'Decoration', ua: 'Прикраса', ru: 'Украшение' },
      { en: 'Surprise', ua: 'Сюрприз', ru: 'Сюрприз' },
    ]
  },
  {
    id: 'office', label: 'Канцтовари та офіс', accent: '#7A6B4E', icon: 'paperclip',
    words: [
      { en: 'Pen', ua: 'Ручка', ru: 'Ручка' },
      { en: 'Paper', ua: 'Папір', ru: 'Бумага' },
      { en: 'Folder', ua: 'Папка', ru: 'Папка' },
      { en: 'Stapler', ua: 'Степлер', ru: 'Степлер' },
      { en: 'Scissors', ua: 'Ножиці', ru: 'Ножницы' },
      { en: 'Glue', ua: 'Клей', ru: 'Клей' },
      { en: 'Eraser', ua: 'Гумка', ru: 'Ластик' },
      { en: 'Marker', ua: 'Маркер', ru: 'Маркер' },
      { en: 'Envelope', ua: 'Конверт', ru: 'Конверт' },
      { en: 'Stamp', ua: 'Марка', ru: 'Марка' },
      { en: 'Calculator', ua: 'Калькулятор', ru: 'Калькулятор' },
      { en: 'Calendar', ua: 'Календар', ru: 'Календарь' },
      { en: 'Whiteboard', ua: 'Біла дошка', ru: 'Белая доска' },
      { en: 'Document', ua: 'Документ', ru: 'Документ' },
      { en: 'Signature', ua: 'Підпис', ru: 'Подпись' },
      { en: 'Meeting room', ua: 'Переговорна кімната', ru: 'Переговорная комната' },
      { en: 'Paper clip', ua: 'Скріпка', ru: 'Скрепка' },
      { en: 'Tape', ua: 'Скотч', ru: 'Скотч' },
      { en: 'Highlighter', ua: 'Текстовиділювач', ru: 'Текстовыделитель' },
      { en: 'Business card', ua: 'Візитівка', ru: 'Визитка' },
    ]
  },
  {
    id: 'grammar', label: 'Прийменники та питальні слова', accent: '#5A6B7A', icon: 'compass',
    words: [
      { en: 'In', ua: 'У / В', ru: 'В' },
      { en: 'On', ua: 'На', ru: 'На' },
      { en: 'Under', ua: 'Під', ru: 'Под' },
      { en: 'Over', ua: 'Над', ru: 'Над' },
      { en: 'Between', ua: 'Між', ru: 'Между' },
      { en: 'Behind', ua: 'Позаду', ru: 'Позади' },
      { en: 'In front of', ua: 'Перед', ru: 'Перед' },
      { en: 'Next to', ua: 'Поруч з', ru: 'Рядом с' },
      { en: 'Inside', ua: 'Всередині', ru: 'Внутри' },
      { en: 'Outside', ua: 'Зовні', ru: 'Снаружи' },
      { en: 'With', ua: 'З', ru: 'С' },
      { en: 'Without', ua: 'Без', ru: 'Без' },
      { en: 'For', ua: 'Для', ru: 'Для' },
      { en: 'From', ua: 'Від', ru: 'От' },
      { en: 'To', ua: 'До', ru: 'До' },
      { en: 'About', ua: 'Про', ru: 'О' },
      { en: 'What', ua: 'Що', ru: 'Что' },
      { en: 'Who', ua: 'Хто', ru: 'Кто' },
      { en: 'Where', ua: 'Де', ru: 'Где' },
      { en: 'When', ua: 'Коли', ru: 'Когда' },
      { en: 'Why', ua: 'Чому', ru: 'Почему' },
      { en: 'How', ua: 'Як', ru: 'Как' },
      { en: 'Which', ua: 'Який', ru: 'Который' },
      { en: 'How many', ua: 'Скільки', ru: 'Сколько' },
      { en: 'Because', ua: 'Тому що', ru: 'Потому что' },
    ]
  },
  {
    id: 'time', label: 'Час і дата', accent: '#3E8C7A', icon: 'clock',
    words: [
      { en: 'Today', ua: 'Сьогодні', ru: 'Сегодня' },
      { en: 'Tomorrow', ua: 'Завтра', ru: 'Завтра' },
      { en: 'Yesterday', ua: 'Вчора', ru: 'Вчера' },
      { en: 'Now', ua: 'Зараз', ru: 'Сейчас' },
      { en: 'Later', ua: 'Пізніше', ru: 'Позже' },
      { en: 'Soon', ua: 'Скоро', ru: 'Скоро' },
      { en: 'Morning', ua: 'Ранок', ru: 'Утро' },
      { en: 'Afternoon', ua: 'День', ru: 'День' },
      { en: 'Evening', ua: 'Вечір', ru: 'Вечер' },
      { en: 'Night', ua: 'Ніч', ru: 'Ночь' },
      { en: 'Week', ua: 'Тиждень', ru: 'Неделя' },
      { en: 'Month', ua: 'Місяць', ru: 'Месяц' },
      { en: 'Year', ua: 'Рік', ru: 'Год' },
      { en: 'Hour', ua: 'Година', ru: 'Час' },
      { en: 'Minute', ua: 'Хвилина', ru: 'Минута' },
      { en: 'Second', ua: 'Секунда', ru: 'Секунда' },
      { en: 'Always', ua: 'Завжди', ru: 'Всегда' },
      { en: 'Never', ua: 'Ніколи', ru: 'Никогда' },
      { en: 'Sometimes', ua: 'Іноді', ru: 'Иногда' },
      { en: 'Early', ua: 'Рано', ru: 'Рано' },
      { en: 'Late', ua: 'Пізно', ru: 'Поздно' },
    ]
  },
  {
    id: 'phrases', label: 'Розмовні фрази', accent: '#8C4E6B', icon: 'message-circle',
    words: [
      { en: 'What time is it?', ua: 'Котра година?', ru: 'Который час?' },
      { en: 'I agree', ua: 'Я згоден/згодна', ru: 'Я согласен/согласна' },
      { en: 'I disagree', ua: 'Я не згоден/згодна', ru: 'Я не согласен/согласна' },
      { en: 'No problem', ua: 'Без проблем', ru: 'Без проблем' },
      { en: 'Of course', ua: 'Звичайно', ru: 'Конечно' },
      { en: 'Maybe', ua: 'Можливо', ru: 'Возможно' },
      { en: "I'm sure", ua: 'Я впевнений/впевнена', ru: 'Я уверен/уверена' },
      { en: "It doesn't matter", ua: 'Це не важливо', ru: 'Это не важно' },
      { en: 'Good luck', ua: 'Успіхів', ru: 'Удачи' },
      { en: 'Take care', ua: 'Бережи себе', ru: 'Береги себя' },
      { en: 'Congratulations!', ua: 'Вітаю!', ru: 'Поздравляю!' },
      { en: 'Welcome', ua: 'Ласкаво просимо', ru: 'Добро пожаловать' },
      { en: 'Make yourself at home', ua: 'Почувайтеся як удома', ru: 'Чувствуйте себя как дома' },
      { en: 'I miss you', ua: 'Я сумую за тобою', ru: 'Я скучаю по тебе' },
      { en: "Let's go", ua: 'Ходімо', ru: 'Пойдём' },
      { en: 'Wait a minute', ua: 'Хвилинку', ru: 'Минутку' },
      { en: "I'm on my way", ua: 'Я вже йду', ru: 'Я уже иду' },
      { en: "What's new?", ua: 'Що нового?', ru: 'Что нового?' },
      { en: "It's up to you", ua: 'Вирішувати тобі', ru: 'Решать тебе' },
      { en: 'Piece of cake', ua: 'Це дуже просто', ru: 'Это проще простого' },
      { en: 'Break a leg', ua: 'Ні пуху, ні пера', ru: 'Ни пуха ни пера' },
      { en: 'Time flies', ua: 'Час летить', ru: 'Время летит' },
      { en: 'Better late than never', ua: 'Краще пізно, ніж ніколи', ru: 'Лучше поздно, чем никогда' },
      { en: 'Practice makes perfect', ua: 'Повторення — мати навчання', ru: 'Повторение — мать учения' },
      { en: 'I will think about it', ua: 'Я подумаю', ru: 'Я подумаю' },
      { en: "It's a deal", ua: 'Домовились', ru: 'Договорились' },
      { en: 'See you soon', ua: 'До швидкої зустрічі', ru: 'До скорой встречи' },
    ]
  },
  {
    id: 'music', label: 'Музика та мистецтво', accent: '#6B4E8C', icon: 'music',
    words: [
      { en: 'Music', ua: 'Музика', ru: 'Музыка' },
      { en: 'Song', ua: 'Пісня', ru: 'Песня' },
      { en: 'Singer', ua: 'Співак', ru: 'Певец' },
      { en: 'Guitar', ua: 'Гітара', ru: 'Гитара' },
      { en: 'Piano', ua: 'Піаніно', ru: 'Пианино' },
      { en: 'Drum', ua: 'Барабан', ru: 'Барабан' },
      { en: 'Violin', ua: 'Скрипка', ru: 'Скрипка' },
      { en: 'Concert', ua: 'Концерт', ru: 'Концерт' },
      { en: 'Band', ua: 'Гурт', ru: 'Группа' },
      { en: 'Dance', ua: 'Танець', ru: 'Танец' },
      { en: 'Painting', ua: 'Картина', ru: 'Картина' },
      { en: 'Drawing', ua: 'Малюнок', ru: 'Рисунок' },
      { en: 'Sculpture', ua: 'Скульптура', ru: 'Скульптура' },
      { en: 'Exhibition', ua: 'Виставка', ru: 'Выставка' },
      { en: 'Photo', ua: 'Фото', ru: 'Фото' },
      { en: 'Film', ua: 'Фільм', ru: 'Фильм' },
      { en: 'Actor', ua: 'Актор', ru: 'Актёр' },
      { en: 'Poem', ua: 'Вірш', ru: 'Стих' },
      { en: 'Rhythm', ua: 'Ритм', ru: 'Ритм' },
      { en: 'Melody', ua: 'Мелодія', ru: 'Мелодия' },
    ]
  },
  {
    id: 'money', label: 'Гроші та банк', accent: '#7A9B3E', icon: 'wallet',
    words: [
      { en: 'Money', ua: 'Гроші', ru: 'Деньги' },
      { en: 'ATM', ua: 'Банкомат', ru: 'Банкомат' },
      { en: 'Loan', ua: 'Кредит', ru: 'Кредит' },
      { en: 'Interest rate', ua: 'Відсоткова ставка', ru: 'Процентная ставка' },
      { en: 'Deposit', ua: 'Депозит', ru: 'Депозит' },
      { en: 'Withdraw', ua: 'Зняти гроші', ru: 'Снять деньги' },
      { en: 'Transfer', ua: 'Переказ', ru: 'Перевод' },
      { en: 'Currency', ua: 'Валюта', ru: 'Валюта' },
      { en: 'Dollar', ua: 'Долар', ru: 'Доллар' },
      { en: 'Euro', ua: 'Євро', ru: 'Евро' },
      { en: 'Hryvnia', ua: 'Гривня', ru: 'Гривна' },
      { en: 'Coin', ua: 'Монета', ru: 'Монета' },
      { en: 'Banknote', ua: 'Банкнота', ru: 'Банкнота' },
      { en: 'Budget', ua: 'Бюджет', ru: 'Бюджет' },
      { en: 'Savings', ua: 'Заощадження', ru: 'Сбережения' },
      { en: 'Debt', ua: 'Борг', ru: 'Долг' },
      { en: 'Income', ua: 'Дохід', ru: 'Доход' },
      { en: 'Expense', ua: 'Витрата', ru: 'Расход' },
      { en: 'Wallet', ua: 'Гаманець', ru: 'Кошелёк' },
      { en: 'Tax', ua: 'Податок', ru: 'Налог' },
    ]
  },
];
